name: Scheduled Tests

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install latest dependencies
      run: |
        python -m pip install --upgrade pip
        # Install with latest versions (not pinned)
        pip install -e . --upgrade
        pip install pytest pytest-cov flake8 black mypy --upgrade
    
    - name: Run tests
      run: |
        pytest -v
    
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check || true  # Don't fail the build, just report